### PR TITLE
Fixed a regression where floats were rounded incorrectly when no minValue was provided

### PR DESCRIPTION
**Pull request by Supereg**
## :recycle: Current situation

The release of v0.10.3 introduced fixes to the float rounding mechanism (see #956, #958). It introduced a regression when no `minValue` was provided (see #971).

## :bulb: Proposed solution

This PR introduces a fix for this regression.

## :gear: Release Notes

* Fixed a regression where floats were rounded incorrectly when no `minValue` was provided

## :heavy_plus_sign: Additional Information

This regression slipped through in this review step: https://github.com/homebridge/HAP-NodeJS/pull/958/files#r893353790.

### Testing

A regression test was added, covering this case.

### Reviewer Nudging

--

### CODE REVIEW

**Comment by Supereg** [comment]
CC: @OrigamiDream

**Comment by OrigamiDream** [comment]
In my opinion, `minValue` and `maxValue` must be **defined** in characteristic level.

Current state:
```typescript
const numericMin = maxWithUndefined(this.props.minValue, numericLowerBound(this.props.format));
const numericMax = minWithUndefined(this.props.maxValue, numericUpperBound(this.props.format));
```

And new suggestion:
```typescript
/* Needs to find original props */
const originalMin = originalProps.minValue; // if there is no defined default values, code must be failed.
const originalMax = originalProps.maxValue;
const numericMin = Math.max(numericLowerBound(this.props.format), maxWithUndefined(this.props.minValue, originalMin));
const numericMax = Math.min(numericUpperBound(this.props.format), maxWithUndefined(this.props.maxValue, originalMax));
```
This is not only preventing setting values to exceeding their limits, but also falling back to specific reasonable default value when the developer haven't set its specific value.
No other changes needed except finding original properties.

All characteristic have their min and max values in their definitions.
But what if developers ignore those values on specific purpose?
The code would be failed because it is not correct operation.
Therefore, those values must be `required`, not `optional` even custom characteristic.

We have to restrict this to developers, not avoiding faced problem.

**Comment by ebaauw** [comment]
> In my opinion, minValue and maxValue must be defined in characteristic level.

I don’t disagree, but then please issue a warning when these are missing instead.

**Review by ebaauw — COMMENTED** [review]
Also happy to see a warning when minValue and maxValue are missing, and leave the 0.10.3 logic.

I do remember issues with setting minValue for temperature to -273.15, because the minStep 0.1 would indeed start there, and no longer accept 20.5.

**Comment by Supereg** [comment]
> I do remember issues with setting minValue for temperature to -273.15, because the minStep 0.1 would indeed start there, and no longer accept 20.5.

That's correct behaviour then.

What I'm proposing is the following logic:

1) `minStep` is **always** (by specification) relative to the `minValue`. Meaning you example I cited above is correct to be rejected.
2) When the developer doesn't specify a `minValue`, we want to have a) to allow a value in the whole number space (e.g. choosing the lowest possible value for the data type) but b) want to use `0` as the reference point for `minStep` (this feels the most natural to me and what developers would expect if they set no value restrictions).

Requiring the `minValue` to be set is a regression as a) the change wasn't described in the previous PR b) there is no check if `minValue` is set, no warnings and no documentation about it (we even have fallback code for other things not requiring `minValue` to be set) and c) this change isn't allowed from a SemVer perspective.

Therefore, I would propose to merge this PR as is for a 0.10.4 release. We could open a discussion separately if we should change the behaviour for a future minor or major version increment of HAP-NodeJS.

**Comment by OrigamiDream** [comment]
If this PR doesn't break any logics from 0.10.3 when `minValue` is specified, this is good to be merged for hot fix purpose.
And well, I had mentioned about this problem when my previous PR have been reviewed.
- https://github.com/homebridge/HAP-NodeJS/pull/958#issuecomment-1152231069

**Comment by Supereg** [comment]
> If this PR doesn't break any logics from 0.10.3 when minValue is specified, this is good to be merged for hot fix purpose.

This PR only changes the logic in the case where `minValue` isn't present. So it doesn't alter any behaviour corrected in any of the previous PPs.

**Review by ebaauw — APPROVED** [review]

**Pull request merged**
