### PR TITLE
Add HomeKit Secure Video & HomeKit Wi-Fi Router support

### PR DESCRIPTION
**Pull request by codyc1515**
Currently does not appear to be working in the Home app, but it makes the options show up.

Feedback welcomed.

### CODE REVIEW

**Comment by Supereg** [comment]
The datastream part ist pretty much finished. In the same branch is currently also the Siri remote part in development, which is still not quite finished.

Your PR currently only includes Service and characteristics definitions. The whole logic is still missing. Hence the question if you have any information where to start digging for the exact logic.

**Comment by Supereg** [comment]
The datastream part ist pretty much finished. In the same branch is currently also the Siri remote part in development, which is still not quite finished.

Your PR currently only includes Service and characteristics definitions. The whole logic is still missing. Hence the question if you have any information where to start digging for the exact logic

**Comment by Supereg** [comment]
I didn‘t research that topic at all, yet. Where did you get the information. I hear people talk about Datastreams needed for that feature? 
Got a working implementation of that in my fork, so I would be Interested how that plays in

**Comment by codyc1515** [comment]
I'm not sure. Could we merge the two and see what it looks like, @Supereg?

**Comment by codyc1515** [comment]
I got the information from the file in `/System/Library/PrivateFrameworks/HomeKitDaemon.framework/Versions/A/Resources/plain-metadata.config`. Unfortunately, I don't have any further information from analysing the other files. You may very well be right about the data streams given that the camera is only streaming when I look at it when it should be streaming all of the time if the home Hub is going to be analysing the data.

There is also a HomeAI.framework in the same area of the macOS filesystem. Looking in there it appears to include support for detecting people, animals and vehicles. Looking here may be able to help you.

Here are some screenshots I took:

IMG_1498
IMG_1499
IMG_1500
IMG_1501
IMG_1502
Screen Shot 2019-11-03 at 20 13 20
Screen Shot 2019-11-03 at 20 14 33

**Comment by Supereg** [comment]
Thanks, maybe I can dig a little deeper if I got any spare time

**Comment by codyc1515** [comment]
I have also added the HomeKit Wi-Fi Routers. These do not work currently and cannot even be paired. I am going to assume that almost certainly something more is required here.

**Comment by Supereg** [comment]
Is the `wifi-satellite` service also related to the HomeKit router stuff?

Also are the `tunnel` and `cloud-relay` services new? Or just not added to HAP-NodeJS. Also anybody has an idea of the purpose of those two?

**Comment by KhaosT** [comment]
Yeah `wifi-satellite` is the extension node. Like range extender in Netgear Orbi's model.

`tunnel` and `cloud-relay` are not new, and both are dead as of iOS 13 😝 Tunnel service was originally created to allow accessory manufacturer to create "bridge" accessory to extend range of BLE accessory. Cloud Relay is to allow accessory manufacturer to support controlling accessory remotely without a home hub (talk directly to iCloud/IDS). Both were deprecated due to lack of adoption.

**Comment by Supereg** [comment]
So I assume products like the Eve Extend do not use the outdated `tunnel` service? 😅 
Thanks for the clarification. Is `could-relay` equivalent to the 'HAP over iCloud' stuff (which requires MFi authentication and so on)? The relay related code in HAP-NodeJS was meant to support cloud-relay service some time ago I guess?

**Comment by KhaosT** [comment]
@Supereg Initially they had a product implemented that, but since Apple never allowed them to ship that (because the tunnel stuff is broken at fundamental level after HAP-BLE 2.0), I believe they switched their in-house solution to have range extender take over HAP part completely...

Yeah it's the HAP over iCloud. There is a private implementation of that based on this repo, but since it requires MFi, it was never available to public 😉

**Comment by Supereg** [comment]
Yeah I still remember that.

Sounds pretty interesting 😅 but probably useless without the ability to compute the MFi challenge. Why does Apple always need to keep the interesting tidbits private 😂

**Comment by Supereg** [comment]
@codyc1515 you did not have any chance to pair the wifi router didn't you? It seems like the wifi stuff should be implemented 🤔 But idk, maybe that are only leftover what I'm seeing here

**Comment by codyc1515** [comment]
Agree that it’s disappointing that HAP over iCloud was never implemented. I have not put the wifi satellite in here yet but can add it shortly. The wifi router will not pair. I suspect it’s looking for a specific tlv8 response which I do not know how to provide as yet (there are no routers in public).

**Comment by Supereg** [comment]
Do you checked the log output after which step the pairing fails?
On the other hand, there are probably other things to do with greater priority than routers 😅 
Should we maybe create dedicated issues for secure video and routers which discuss the reverse engineering process of both?

**Comment by codyc1515** [comment]
Some more screenshots.

IMG_1509
IMG_1510

**Comment by hassbian-ABC** [comment]
@codyc1515 I can't add it to the home app

**Comment by hassbian-ABC** [comment]
How did you do it @codyc1515

**Comment by codyc1515** [comment]
This is the log from when I try to pair. Looks like the Home app doesn't like the Accessory for some reason.

```
pi@raspi4:~/HAP-NodeJS $ sudo DEBUG=* ts-node --files src/Core.ts
HAP-NodeJS starting...
  AccessoryLoader Parsing accessory: WiFi-Router_accessory.ts +0ms
  EventedHTTPServer Server listening on port 51926 +358ms
  EventedHTTPServer [::ffff:172.16.32.111] New connection from client +50s
  EventedHTTPServer [::ffff:172.16.32.111] HTTP server listening on port 42557 +2ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP request: /pair-setup +29ms
  HAPServer [FA:3C:ED:5A:1A:A1] HAP Request: POST /pair-setup +1ms
  HAPServer [FA:3C:ED:5A:1A:A1] Pair step 1/5 +10ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP Response is finished +469ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP request: /pair-setup +2s
  HAPServer [FA:3C:ED:5A:1A:A1] HAP Request: POST /pair-setup +1ms
  HAPServer [FA:3C:ED:5A:1A:A1] Pair step 2/5 +2ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP Response is finished +372ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP request: /pair-setup +28ms
  HAPServer [FA:3C:ED:5A:1A:A1] HAP Request: POST /pair-setup +0ms
  HAPServer [FA:3C:ED:5A:1A:A1] Pair step 3/5 +1ms
  HAPServer [FA:3C:ED:5A:1A:A1] Pair step 4/5 +8ms
  HAPServer [FA:3C:ED:5A:1A:A1] Pair step 5/5 +121ms
  Accessory [Wi-Fi Router] Paired with client AA5731A6-EAC2-4B9A-98B9-5BB8263BF921 +35ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:172.16.32.111] Client connection closed +171ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP server was closed +1ms
  EventedHTTPServer [::ffff:172.16.32.111] New connection from client +5ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP server listening on port 35793 +0ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP request: /pair-verify +2ms
  HAPServer [FA:3C:ED:5A:1A:A1] HAP Request: POST /pair-verify +0ms
  HAPServer [FA:3C:ED:5A:1A:A1] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP Response is finished +49ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP request: /pair-verify +27ms
  HAPServer [FA:3C:ED:5A:1A:A1] HAP Request: POST /pair-verify +0ms
  HAPServer [FA:3C:ED:5A:1A:A1] Pair verify step 2/2 +1ms
  HAPServer [FA:3C:ED:5A:1A:A1] Client AA5731A6-EAC2-4B9A-98B9-5BB8263BF921 verification complete +53ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP request: /accessories +44ms
  HAPServer [FA:3C:ED:5A:1A:A1] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP request: /pairings +169ms
  HAPServer [FA:3C:ED:5A:1A:A1] HAP Request: POST /pairings +1ms
  HAPServer [FA:3C:ED:5A:1A:A1] Pairings: successfully executed REMOVE_PAIRING +5ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:172.16.32.111] Client connection closed +13ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:172.16.32.111] HTTP server was closed +1ms
```

Here is the plugin I made, based on the Lightbulb accessory:

```
import {
  Accessory,
  AccessoryEventTypes,
  Characteristic,
  CharacteristicEventTypes, CharacteristicSetCallback,
  CharacteristicValue,
  NodeCallback,
  Service,
  uuid,
  VoidCallback
} from '..';

class wifiControllerClass {

  name: CharacteristicValue = "Wi-Fi Router"; //name of accessory
  pincode: CharacteristicValue = "031-45-154";
  username: CharacteristicValue = "FA:3C:ED:5A:1A:A1"; // MAC like address used by HomeKit to differentiate accessories.
  manufacturer: CharacteristicValue = "HAP-NodeJS"; //manufacturer (optional)
  model: CharacteristicValue = "v1.0"; //model (optional)
  serialNumber: CharacteristicValue = "A12S345KGB"; //serial number (optional)

  power: CharacteristicValue = false; //current power status

  outputLogs = true; //output logs

  setPower(status: CharacteristicValue) { //set power of accessory
    if(this.outputLogs) console.log("Turning the '%s' %s", this.name, status ? "on" : "off");
    this.power = status;
  }

  getPower() { //get power of accessory
    if(this.outputLogs) console.log("'%s' is %s.", this.name, this.power ? "on" : "off");
    return this.power;
  }

  identify() { //identify the accessory
    if(this.outputLogs) console.log("Identify the '%s'", this.name);
  }
}

const wifiController = new wifiControllerClass();

var lightUUID = uuid.generate('hap-nodejs:accessories:light' + wifiController.name);

var wifiAccessory = exports.accessory = new Accessory(wifiController.name as string, lightUUID);

// @ts-ignore
wifiAccessory.username = wifiController.username;
// @ts-ignore
wifiAccessory.pincode = wifiController.pincode;

wifiAccessory
  .getService(Service.AccessoryInformation)!
    .setCharacteristic(Characteristic.Manufacturer, wifiController.manufacturer)
    .setCharacteristic(Characteristic.Model, wifiController.model)
    .setCharacteristic(Characteristic.SerialNumber, wifiController.serialNumber);

wifiAccessory.on(AccessoryEventTypes.IDENTIFY, (paired: boolean, callback: VoidCallback) => {
  wifiController.identify();
  callback();
});

wifiAccessory
  .addService(Service.WiFiRouter, wifiController.name)
  .getCharacteristic(Characteristic.RouterStatus)!
  .on(CharacteristicEventTypes.SET, (value: CharacteristicValue, callback: CharacteristicSetCallback) => {
    wifiController.setPower(value);
    callback();
  })
  .on(CharacteristicEventTypes.GET, (callback: NodeCallback<CharacteristicValue>) => {
    callback(null, wifiController.getPower());
  });
```

**Comment by hassbian-ABC** [comment]
77A471795819AAC91F1A0AA19CC40DDA
0A8DA4CAB26EBAC134B1043D2FEB676E

**Comment by hassbian-ABC** [comment]
This is what I did before, but I can't add it to the home app @codyc1515

**Comment by codyc1515** [comment]
@hassbian-ABC Yes, it currently does not work & I am not sure why as there is no reference device or documentation.

**Comment by Supereg** [comment]
Okay so the current state is, that HomeKit pairs but after executing the initial `GET /accessories` it automatically unpairs itself.
What I also found out that in order to add a HomeKit router to your home you need to have some sort of home hub configured. Otherwise the pairing process will be aborted.

I think what happens is, that HAP expects some sort of default configuration the the `GET /accessories` which are obviously unknown/not set. So I'm unsure what the best way is to proceed at this point. Besides that, I'm much more interested in Secure Video than routers 😅

**Comment by Supereg** [comment]
Okay i found the problem looking in the console while pairing. You simply didn't set the permissions correctly for the characteristics. Correcting the permissions it pairs just fine.

**Comment by Supereg** [comment]
Some of them were correct. I listed all newly added characteristics with their permission below. Would be great if you could update the PR.

Camera:
* RecordingAudioActive: READ, WRITE, NOTIFY, TIMED_WRITE
* SupportedCameraRecordingConfiguration: READ, NOTIFY
* SupportedVideoRecordingConfiguration: READ, NOTIFY
* SupportedAudioRecordingConfiguration: READ, NOTIFY
* SelectedCameraRecordingConfiguration: READ, WRITE; NOTIFY
* CameraOperatingModeIndicator: READ, WRITE, NOTIFY, TIMED_WRITE
* EventSnapshotsActive: READ, WRITE, NOTIFY, TIMED_WRITE
* HomeKitCameraActive: READ, WRITE, NOTIFY, TIMED_WRITE
* ManuallyDisabled: READ, NOTIFY
* ThirdPartyCameraActive: READ, NOTIFY
* PeriodicSnapshotsActive: READ, WRITE, NOTIFY, TIMED_WRITE


Router:
* NetworkClientControl: READ, WRITE, NOTIFY, TIMED_WRITE, WRITE_RESPONSE,
* NetworkClientStatusControl: READ, WRITE, WRITE_RESPONSE
* RouterStatus: READ, NOTIFY
* SupportedRouterConfiguration: READ
* WANConfigurationList: READ, NOTIFY
* WANStatusList: READ, NOTIFY
* ManagedNetworkEnable: READ, WRITE, NOTIFY, TIMED_WRITE
* NetworkAccessViolationControl: READ, WRITE, NOTIFY, TIMED_WRITE, WRITE_RESPONSE

**Comment by Supereg** [comment]
What I found out so far:

* You need to have a home hub to pair a router accessory
* The name of the accessory should match the WLAN SSID

**Comment by codyc1515** [comment]
I have also added some bug fixes to this commit which are not related to Secure Video or Wi-Fi Router. I'm not sure how to split these out unfortunately.

**Comment by codyc1515** [comment]
I also don't know how the TLV8 structures work exactly. I have made the permissions changes and now have the accessory paired. Here are some screenshots (thank you to @Supereg !):

IMG_1545
IMG_1546
IMG_1547
IMG_1548
IMG_1549

**Comment by Supereg** [comment]
I probably should investigate this while having some accessories paired in my test home 😅 Didn't know you get the connected accessories displayed in the router overview. Thanks for the hint 🙃
Im also unsure what exact structure the tlv8 has. Length and exact meaning of some values is pretty problematic. But should I get access to an HAP enabled router I think we could solve this with the information we get from the binaries.

**Comment by codyc1515** [comment]
Cool. Thank you. Would you please be able to take a moment to explain how you worked out the TLV8 structure and the permissions issues? You mentioned about a log somewhere?

**Comment by Supereg** [comment]
Regarding the permission stuff: I just opened the console app on macOS and viewed the log output of my iPhone of the `homed` process while trying to pair the router. There I encountered a warning message that HomeKit expected a TIMED_WRITE permission on some characteristic. That gave me the clue.
The permission itself stands in the already mentioned plist file. It's encoded in the `Properties` key for every characteristic. The permissions are encoded as bit masks in a single number. Under `Root.PlistDictionary.HAP.Properties` are all the possible permissions listed with their designated bit position.

**Comment by codyc1515** [comment]
Going to close this pull request and make some separate pull requests as there is too much in here.

**Comment by netRunner0** [comment]
https://blog.logitech.com/2019/11/14/circle-2-now-works-with-apple-homekit-secure-video/

**Comment by netRunner0** [comment]
@Supereg Any new info on tlv8?

**Comment by HappyStriker** [comment]
This is a very interessting discussion and I have tried to implement a custom node hap based router in the past, but without success.
Unfortunately I did not find a clue on how to solve the whole tlv8 situation to be actually able to control the network permissions of all of my IoT devices.
Are there any updates or documentation on this topic and how to use it?
Thank you very much!

**Comment by redelva** [comment]
> I also don't know how the TLV8 structures work exactly. I have made the permissions changes and now have the accessory paired. Here are some screenshots (thank you to @Supereg !):
> 
> IMG_1545 IMG_1546 IMG_1547 IMG_1548 IMG_1549

are there any examples of homekit secure router implementations?

i am interested in homekit secure router and just figure out the api of asus routers.

just wanna to implement it.

**Comment by thiccaxe** [comment]
@redelva the linksys mx4200 is listed as a supported router by Apple. The firmware image is available online. Based on the files inside, there does appear to be homekit support.

**Pull request closed without merging**
