### PR TITLE
Attach to interface

### PR DESCRIPTION
**Pull request by Roman1us**
Allow set host for HAP server #695

### CODE REVIEW

**Comment by KhaosT** [comment]
Should we also update Advertiser to only advertise on the given interface?

**Comment by Supereg** [comment]
> Should we also update Advertiser to only advertise on the given interface?

Would be relatively important. @Roman1us could you add that?

**Comment by Roman1us** [comment]
> > Should we also update Advertiser to only advertise on the given interface?
> 
> Would be relatively important. @Roman1us could you add that?

Thinking about it, but we have a mdns object in configuration. In tests with mDNSResponder and avahi-daemon run in system i've got problems with attaching to interfaces that already use this interface

**Comment by Roman1us** [comment]
Have somthing to discuss?

**Comment by Supereg** [comment]
Will probably ship with v0.8.0, needs some work in the underlying mdns library

**Comment by Roman1us** [comment]
> Will probably ship with v0.8.0, needs some work in the underlying mdns library

Ok, i'm going to test ciao library in different environments

**Comment by Supereg** [comment]
alright, so with a little bit of delay, the feature was finally implemented and will ship with the next release (follow [release cycle](https://github.com/homebridge/HAP-NodeJS/projects/4)).

The feature was implemented in a separate commit, as it is a bit more sophisticated and provides much greater control (and as it required additional tailoring to properly change the interface in the advertising library). So the PR will just be closed.
Nonetheless thanks for your contribution, as this was the fundamentally necessary starter for this change.

The new `bind` publish option, can be a string or array of strings containing ip addresses or network interface names.
For the best overview on how it works, you may just read the documentation linked below.
The feature is currently still in beta. Feel free to test if you want.

https://github.com/homebridge/HAP-NodeJS/blob/e858e39576d1b4282d477b78d0e432f417721a03/src/lib/Accessory.ts#L156-L203

**Pull request closed without merging**
