### PR TITLE
AdaptiveLightingController fix & improvement

### PR DESCRIPTION
**Pull request by Shaquu**
## :recycle: Current situation

*Describe the current situation. Explain current problems, if there are any. Be as descriptive as possible (e.g., including examples or code snippets).*

Would be great to have update data provided from update event.
Also noticed few type issues, now properly using optional chaining.

## :bulb: Proposed solution

*Describe the proposed solution and changes. How does it affect the project? How does it affect the internal structure (e.g., refactorings)?*

Would be great to have update data provided from update event.
Also noticed few type issues, now properly using optional chaining.

## :gear: Release Notes

*Provide a summary of the changes or features from a user's point of view. If there are breaking changes, provide migration guides using code examples of the affected features.*

AdaptiveLightingController: Update payload added to update event.
AdaptiveLightingController: Resolve possible TypeError, related to incorrect optional values unwrapping.

## :heavy_plus_sign: Additional Information
*If applicable, provide additional context in this section.*

### Testing

*Which tests were added? Which existing tests were adapted/changed? Which situations are covered, and what edge cases are missing?*

N/A

### Reviewer Nudging

*Where should the reviewer start? what is a good entry point?*

Adaptive Lightning API :)

### CODE REVIEW

**Review by donavanbecker — DISMISSED** [review]

**Comment by Shaquu** [comment]
No clue why some checks failed.
`typedoc` complains about `@since iOS 14` which is not scope of my change
`pr labeler` cannot start at all

**Review by donavanbecker — DISMISSED** [review]

**Review by donavanbecker — DISMISSED** [review]

**Comment by Shaquu** [comment]
Ahh @donavanbecker I see I did the same as you. Not sure if good. Should it target latest or beta?

**Comment by donavanbecker** [comment]
> Ahh @donavanbecker I see I did the same as you. Not sure if good. Should it target latest or beta?

lets do beta. We can then do a quick Homebridge beta before release this version.

**Comment by bwp91** [comment]
- this won't cause any issues with existing plugins that use adaptive lighting API right? (just wanted to confirm)
- it would be nice if you could update `src/accessories/Light-AdaptiveLighting_accessory.ts` with perhaps just a simple way of showing how the new update information can be retrieved

**Comment by Shaquu** [comment]
Good point. Let me check for both, let's not rush it.

**Comment by bwp91** [comment]
also if you update your branch from the beta branch, you should find the build issues are all fixed 👍

**Comment by Shaquu** [comment]
@bwp91 

> * this won't cause any issues with existing plugins that use adaptive lighting API right? (just wanted to confirm)

With the new parameter in listener, you can still use listener without a parameter. So current implementations should be all right.

> * it would be nice if you could update `src/accessories/Light-AdaptiveLighting_accessory.ts` with perhaps just a simple way of showing how the new update information can be retrieved

Updated, but as `AUTOMATIC` is default I put some comments and some code.

**Comment by Shaquu** [comment]
Anyone, `PR Labeler / stale / update_release_draft (pull_request) ` failing
image

**Review by donavanbecker — APPROVED** [review]

**Pull request merged**
